(function() {var implementors = {};
implementors['dstr'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a, Sep: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.CharSplits.html' title='dstr::CharSplits'>CharSplits</a>&lt;'a, Sep&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a, Sep: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.CharSplitsN.html' title='dstr::CharSplitsN'>CharSplitsN</a>&lt;'a, Sep&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.MatchIndices.html' title='dstr::MatchIndices'>MatchIndices</a>&lt;'a&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.StrSplits.html' title='dstr::StrSplits'>StrSplits</a>&lt;'a&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.Chars.html' title='dstr::Chars'>Chars</a>&lt;'a&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.CharOffsets.html' title='dstr::CharOffsets'>CharOffsets</a>&lt;'a&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dstr/struct.Utf16CodeUnits.html' title='dstr::Utf16CodeUnits'>Utf16CodeUnits</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
